# Generated by Django 5.1.3 on 2024-12-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0002_bed_bedapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='is_available',
            field=models.IntegerField(),
        ),
    ]
