# Generated by Django 5.1.3 on 2024-12-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0003_alter_bed_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
