# Generated by Django 5.1.3 on 2024-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0008_alter_appointment_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physical_Therappy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
