# Generated by Django 5.1.3 on 2024-12-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0012_alter_appointment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
