# Generated by Django 5.1.3 on 2024-12-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0014_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status_notes',
            field=models.TextField(blank=True, help_text='Additional notes about status change', null=True),
        ),
    ]
