# Generated by Django 5.1.3 on 2024-12-12 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0016_disease_medicine_patient_prescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status_notes',
        ),
    ]
