# Generated by Django 5.1.3 on 2024-12-17 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosp', '0022_alter_appointment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hosp.appointment'),
        ),
        migrations.AlterField(
            model_name='billinginvoice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='hosp.appointment'),
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
